# MCTS config
episodes: 10
simulations: 300 # m
epsilon: 1
epsilon_decay: 1
sigma: 1
sigma_decay: 1
c: 1.3

# Neural Network config
nr_of_anets: 5 # m
rbuf_size: 512
learning_rate: 0.001
activation: relu # linear, sigmoid, tanh, relu, leaky_relu, tanh
optimizer: adam # Adagrad, Stochastic Gradient Descent (SGD), RMSProp, and Adam
loss: cross_entropy # mse, cross_entropy, l1
batch_size: 128
plot_accuracy: false
move_cap: 200
sample_ratio: 0.8

# GO config
board_size: 5 # k

# Debug config
visualize_tree: false
render: true

# Topp config
nr_of_topp_games: 25 # g