# MCTS config
episodes: 3000
simulations: 100 # m
epsilon: 1.0 # rollout
epsilon_decay: 0.002
sigma: 1.0 # critic
sigma_decay: 0.0007
alpha: 0.2 # Selecting move randomly, but weighted by the distribution (0 = argmax, 1 = probablistic)
alpha_decay: 0.0007
c: 1.3

# Neural Network config
nr_of_anets: 20 # m
learning_rate: 0.001
move_cap: 200

# Replay buffer config
rbuf_size: 2048 # Single process
rbuf_cap: 10000 # Multi process
sample_ratio: 0
batch_size: 512

# Tensorboard config
log_dir: tensorboard_logs
log_name: go

# GO config
board_size: 5 # k
komi: 0
canonical_board: false

# Threads
multi_process: false
nr_of_threads: 4
epochs: 10
epoch_skip: 0

# System
use_gpu: false

# Debug config
render: false
plot: false

# Topp config
nr_of_topp_games: 2 # g