# MCTS config
episodes: 1
simulations: 100 # m
epsilon: 1
epsilon_decay: 1
sigma: 1
sigma_decay: 1
c: 1.3

# Neural Network config
nr_of_anets: 5 # m
rbuf_size: 512
rbuf_cap: 10000
learning_rate: 0.001
batch_size: 128
plot_accuracy: false
move_cap: 200
sample_ratio: 0.8

# GO config
board_size: 5 # k
komi: 0

# Threads
multi_threading: true
nr_of_threads: 6
epochs: 10
epoch_skip: 0

# System
use_gpu: false

# Debug config
visualize_tree: false
render: true
plot: false

# Topp config
nr_of_topp_games: 1 # g