# MCTS config
episodes: 10000 # Single process
episodes_per_epoch: 10 # Multi process
simulations: 500 # m
c: 1.3 # Exploration constant
det_moves: 5 # Number of plies to use for non-deterministic playouts
epochs: 100
epoch_skip: 0

# Neural Network config
resnet: false
resnet_blocks: 3 # n
resnet_filters: 64 # f
convnet_filters: 32 # f
nr_of_anets: 10 # m
learning_rate: 0.001
pre_trained: false # Remember to set sigma and epsilon to 0 for faster training
pre_trained_path: ../models/pre_trained/board_size_5/

# Replay buffer config
rbuf_size: 2048 # Single process (2048)
rbuf_cap: 30000 # Multi process
sample_ratio: 0.3 # 50% chance of adding case to replay buffer, helps with overfitting
batch_size: 512 # 512
clear_rbuf: false

# Tensorboard config
log_dir: tensorboard_logs
log_name: go

# GO config
board_size: 9 # k
komi: 5.5 # gives white a bonus of x points at the end of the game due to black going first
move_cap: 200

# Debug config
render: false
plot: false

# Topp config
nr_of_topp_games: 2 # g