# MCTS config
episodes: 3000
simulations: 100 # m
epsilon: 1.0 # rollout
epsilon_decay: 0.002
sigma: 1.0 # critic
sigma_decay: 0.0007
alpha: 0.2 # Selecting move randomly, but weighted by the distribution (0 = argmax, 1 = probablistic)
alpha_decay: 0.0007
c: 1.3

# Neural Network config
nr_of_anets: 20 # m
rbuf_size: 2048
rbuf_cap: 10000
learning_rate: 0.001
batch_size: 512
plot_accuracy: false
move_cap: 200
sample_ratio: 0.8

# Tensorboard config
log_dir: tensorboard_logs
log_name: go

# GO config
board_size: 5 # k
komi: 0

# Threads
multi_process: false
nr_of_threads: 4
epochs: 10
epoch_skip: 0

# System
use_gpu: false

# Debug config
render: false
plot: true

# Topp config
nr_of_topp_games: 2 # g